name: Secret & Artifact Demo

on: [push]

jobs:
  secret-env-demo:
    runs-on: ubuntu-latest
    environment: Staging   # optional, requires approval if set

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Print secret (hidden in logs)
        run: echo "Secret is ${{ secrets.MY_SECRET }}"

      - name: Run test script
        run: ./scripts/test.sh | tee test.log

      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: test.log

